### PR TITLE
Remove the jquery dependency

### PR DESCRIPTION
**Pull request by foolip**
With this change no further jquery remains in package-lock.json.

### CODE REVIEW

**Comment by Hexcles** [comment]
The staging deployment https://rm-jquery-dep-dot-web-confluence.appspot.com looks correct to me. I'm merging this PR.

**Comment by foolip** [comment]
Cool, having staging deployment working again makes things easier :)

**Comment by foolip** [comment]
Turns out this did break stuff, the broken graphs I've mentioned in https://github.com/GoogleChromeLabs/confluence/issues/350#issuecomment-483144079 seem to be because of a jQuery dependency. Trying to sever it now.

**Comment by Hexcles** [comment]
Sigh, having to ship jQuery is tremendously unfortunate.

**Comment by foolip** [comment]
@Hexcles I was able to avoid it in the end :)

**Pull request merged**
